### ISSUE TITLE
updates: KeyError in pkg_id2repo_id[upd_pkg_id]

### ISSUE THREAD

**Issue by psegedy** [RedHatInsights/vmaas#136]
With following packages
```
vim-enhanced-2:7.4.160-2.el7.x86_64
vim-common-2:7.4.160-2.el7.x86_64
vim-minimal-2:7.4.160-1.el7.x86_64
```

I am hitting this error:
```
vmaas-webapp | ERROR:tornado.application:Uncaught exception GET /api/v1/updates/vim-common-2:7.4.160-2.el7.x86_64 (172.18.0.1)
vmaas-webapp | HTTPServerRequest(protocol='http', host='localhost:8080', method='GET', uri='/api/v1/updates/vim-common-2:7.4.160-2.el7.x86_64', version='HTTP/1.1', remote_ip='172.18.0.1', headers={'Host': 'localhost:8080', 'Accept': '*/*', 'User-Agent': 'curl/7.55.1'})
vmaas-webapp | Traceback (most recent call last):
vmaas-webapp |   File "/usr/lib64/python2.7/site-packages/tornado/web.py", line 1412, in _execute
vmaas-webapp |     result = method(*self.path_args, **self.path_kwargs)
vmaas-webapp |   File "/app/app.py", line 19, in get
vmaas-webapp |     response = self.process_string(name)
vmaas-webapp |   File "/app/app.py", line 44, in process_string
vmaas-webapp |     return self.application.updatesapi.process_list({'package_list': [data]})
vmaas-webapp |   File "/app/updates.py", line 269, in process_list
vmaas-webapp |     for r_id in pkg_id2repo_id[upd_pkg_id]:
vmaas-webapp | KeyError: 88458
vmaas-webapp | ERROR:tornado.access:500 GET /api/v1/updates/vim-common-2:7.4.160-2.el7.x86_64 (172.18.0.1) 54.48ms
```

It seems like it looking for fedora package instead of rhel
```sql
vmaas=> select * from evr where id in (select evr_id from package where id = 88458);
  id   | epoch | version  | release |                                   evr                                   
-------+-------+----------+---------+-------------------------------------------------------------------------
 16212 | 2     | 8.0.1553 | 1.fc27  | (2,"{""(8,)"",""(0,)"",""(1553,)""}","{""(1,)"",""(0,fc)"",""(27,)""}")
(1 row)
```

even though there is `vim-common` package in rhel
```sql
vmaas=> select * from package inner join  evr on package.evr_id = evr.id where evr_id in (select evr_id from package where name = 'vim-common') and name = 'vim-common';

  id   |    name    | evr_id | arch_id |                             checksum                             | checksum_type_id |  id   | epoch | version  |  release  |                                           evr                                           
-------+------------+--------+---------+------------------------------------------------------------------+------------------+-------+-------+----------+-----------+-----------------------------------------------------------------------------------------
   559 | vim-common |   6507 |       1 | 93bed1cf7e0724e10f614f2e839e44ba596fc406                         |                1 |  6507 | 2     | 7.4.629  | 5.el6     | (2,"{""(7,)"",""(4,)"",""(629,)""}","{""(5,)"",""(0,el)"",""(6,)""}")
  2911 | vim-common |   2180 |       1 | 923e8a2e85e4612b5c8f7c35c08482002dcd9cff                         |                1 |  2180 | 2     | 7.2.411  | 1.8.el6   | (2,"{""(7,)"",""(2,)"",""(411,)""}","{""(1,)"",""(8,)"",""(0,el)"",""(6,)""}")
  2957 | vim-common |   1764 |       1 | 8cf91f0f612ebdb601637e6a46999fa9dadded6e                         |                1 |  1764 | 2     | 7.2.411  | 1.6.el6   | (2,"{""(7,)"",""(2,)"",""(411,)""}","{""(1,)"",""(6,)"",""(0,el)"",""(6,)""}")
  7021 | vim-common |   5708 |       1 | 58f87e449d39124a44c2b9f14e78eae482a59a8a                         |                1 |  5708 | 2     | 7.4.629  | 5.el6_8.1 | (2,"{""(7,)"",""(4,)"",""(629,)""}","{""(5,)"",""(0,el)"",""(6,)"",""(8,)"",""(1,)""}")
 14201 | vim-common |   5861 |       1 | b29afff72319f5255fb2b53e1a7718b5ac7724c8                         |                1 |  5861 | 2     | 7.2.411  | 1.4.el6   | (2,"{""(7,)"",""(2,)"",""(411,)""}","{""(1,)"",""(4,)"",""(0,el)"",""(6,)""}")
 40757 | vim-common |  12231 |       1 | 84704e35d510631dedd1ee497001c3b1b5113665                         |                1 | 12231 | 2     | 7.4.160  | 1.el7     | (2,"{""(7,)"",""(4,)"",""(160,)""}","{""(1,)"",""(0,el)"",""(7,)""}")
 49171 | vim-common |  10568 |       1 | 9dbb79a05a1eaefec5c587a5fe73d8d489d95d62                         |                1 | 10568 | 2     | 7.4.160  | 2.el7     | (2,"{""(7,)"",""(4,)"",""(160,)""}","{""(2,)"",""(0,el)"",""(7,)""}")
 49808 | vim-common |  12073 |       1 | ac2ac4703400e04e8cb81ba7d65077553d61b198                         |                1 | 12073 | 2     | 7.4.160  | 1.el7_3.1 | (2,"{""(7,)"",""(4,)"",""(160,)""}","{""(1,)"",""(0,el)"",""(7,)"",""(3,)"",""(1,)""}")
 75884 | vim-common |  15560 |       1 | 5054b42407705286e1b529e0baa5f303d723499abd77c9c891b1b1bdc717def7 |                2 | 15560 | 2     | 8.0.1553 | 1.fc26    | (2,"{""(8,)"",""(0,)"",""(1553,)""}","{""(1,)"",""(0,fc)"",""(26,)""}")
 88458 | vim-common |  16212 |       1 | 2441c4ce9568019e9f149f76db848b7f67613f48d582a960d83e9bd99067cae7 |                2 | 16212 | 2     | 8.0.1553 | 1.fc27    | (2,"{""(8,)"",""(0,)"",""(1553,)""}","{""(1,)"",""(0,fc)"",""(27,)""}")
 89278 | vim-common |  17838 |       1 | c5da666beabf2f24dcdf8c3247e005dcd42a0bf5538c0bea9801d5a97c6fabd6 |                2 | 17838 | 2     | 8.0.1573 | 1.fc27    | (2,"{""(8,)"",""(0,)"",""(1573,)""}","{""(1,)"",""(0,fc)"",""(27,)""}")
(11 rows)

```

**Comment by grinrag** [comment]
@psegedy Looks like this issue fixed in my PR #134. Please update your instance of the application, if you still see the problem, feel free to reopen this issue.
