### ISSUE TITLE
reposcan refresh results in lots of tracebacks

### ISSUE THREAD

**Issue by ggainey** [RedHatInsights/vmaas#152]
Updated to latest, and repo/cve scan has started throwing the following tracebacks even when they succeed:

===
...
CVE to CWE mapping to import: 0
Syncing CVEs finished.
CVE sync task finished: OK.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f484e5daeb8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='webapp', port=8079): Max retries exceeded with url: /api/internal/refresh (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f484e5daeb8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/vmaas-reposcan/reposcan.py", line 139, in _notify_webapp
    response = requests.get(refresh_url)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='webapp', port=8079): Max retries exceeded with url: /api/internal/refresh (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f484e5daeb8>: Failed to establish a new connection: [Errno 111] Connection refused',))

Unable to connect to http://webapp:8079/api/internal/refresh.

**Comment by jdobes** [comment]
This is related to #149. But I can't reproduce. reposcan container calls webapp conatiner's API on new internal port to notify that sync was performed and it should regenerate it's cache structures. Here it seems that it can't connect to webapp using the new port. Try to take whole docker compose down and then up again with --build parameter and check if the problem persists.

**Comment by jdobes** [comment]
Such tracebacks are logged for informational and debug purposes when reposcan fails to notify webapp API to refresh it's cache (in this case **devel** docker compose was running but the webapp API wasn't - because it needs to be executed manually in **devel** compose).

This is currently the intended behavior, I suppose the traceback could be hidden in this case because it can be confusing. (at least when default verbosity is used - see #37 )
