### ISSUE TITLE
Attempt to scan repos fails with KeyError: 'products'

### ISSUE THREAD

**Issue by mkoura** [RedHatInsights/vmaas#167]
The request ``POST http://127.0.0.1:8081/api/v1/sync/repo`` fails with
```json
{
	"success": false,
	"msg": "Incorrect JSON format."
}
```
and
```
vmaas-reposcan | Traceback (most recent call last):
vmaas-reposcan |   File "/vmaas-reposcan/reposcan.py", line 230, in post
vmaas-reposcan |     products, repos = self._parse_input_list()
vmaas-reposcan |   File "/vmaas-reposcan/reposcan.py", line 210, in _parse_input_list
vmaas-reposcan |     for product_name, product in repo_group["products"].items():
vmaas-reposcan | KeyError: 'products'
vmaas-reposcan | 
vmaas-reposcan | WARNING:tornado.access:400 POST /api/v1/sync/repo (172.18.0.1) 0.93ms
```

The body I used for the request worked last time I used it, I can strip off the certificate/key data and paste it here if needed.

**Comment by mkoura** [comment]
I see there was a change in the JSON format few days ago, that's probably my issue, closing.
