### ISSUE TITLE
For some repos errata.description can be empty

### ISSUE THREAD

**Issue by ggainey** [RedHatInsights/vmaas#185]
Syncing fedora-repos leads to null for errata.description and an insert-failure:

vmaas-reposcan | Traceback (most recent call last):
vmaas-reposcan |   File "/vmaas-reposcan/reposcan.py", line 55, in repo_sync_task
vmaas-reposcan |     repository_controller.store()
vmaas-reposcan |   File "/vmaas-reposcan/repodata/repository_controller.py", line 208, in store
vmaas-reposcan |     self.repo_store.store(repository)
vmaas-reposcan |   File "/vmaas-reposcan/database/repository_store.py", line 114, in store
vmaas-reposcan |     self.update_store.store(repo_id, repository.list_updates())
vmaas-reposcan |   File "/vmaas-reposcan/database/update_store.py", line 310, in store
vmaas-reposcan |     update_map = self._populate_updates(updates)
vmaas-reposcan |   File "/vmaas-reposcan/database/update_store.py", line 134, in _populate_updates
vmaas-reposcan |     import_data, page_size=len(import_data))
vmaas-reposcan |   File "/usr/lib64/python3.6/site-packages/psycopg2/extras.py", line 1256, in execute_values
vmaas-reposcan |     cur.execute(b''.join(parts))
vmaas-reposcan | psycopg2.IntegrityError: null value in column "description" violates not-null constraint
vmaas-reposcan | DETAIL:  Failing row contains (6991, FEDORA-2018-aed84f4b44, perl-Tree-Simple-1.33-1.fc27, 2, 1, perl-Tree-Simple-1.33-1.fc27 bugfix update, null, null, 2018-01-15 14:51:10+00, 2018-04-01 19:17:31+00).
vmaas-reposcan | Repo sync task finished: ERROR.

We should prob fill w/a default string "NO DESCRIPTION PROVIDED" or something

**Comment by ggainey** [comment]
Or just relax the constraint and let it be what it is. More generally - the db should only enforce constraints that will **break vmaas** (like ids and names being not-null because the code has to have them). Since the app isn't responsible for creating data, it needs to accept whatever it finds when sync'ing, as much as possible.
