### ISSUE TITLE
reposcan: add error handling to avoid tracebacks in the logs.

### ISSUE THREAD

**Issue by grinrag** [RedHatInsights/vmaas#217]
I see some tracebacks in the logs of reposcan:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='webapp', port=8079): Max retries exceeded with url: /api/internal/refresh (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f97a6d03320>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

We need to add error handling here to avoid this mess.

**Comment by grinrag** [comment]
Second traceback I see in containers logs:

--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/usr/lib64/python3.6/logging/__init__.py", line 575, in format
    record.message = record.getMessage()
  File "/usr/lib64/python3.6/logging/__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not NoneType
Call stack:
  File "/vmaas-reposcan/reposcan.py", line 95, in <module>
    class SyncTask:
  File "/vmaas-reposcan/reposcan.py", line 101, in SyncTask
    workers = Pool(1)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 174, in __init__
    self._repopulate_pool()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 239, in _repopulate_pool
    w.start()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 26, in __init__
    self._launch(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 80, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/vmaas-reposcan/reposcan.py", line 67, in repo_sync_task
    repository_controller.store()
  File "/vmaas-reposcan/repodata/repository_controller.py", line 189, in store
    self._read_repomds(failed)
  File "/vmaas-reposcan/repodata/repository_controller.py", line 87, in _read_repomds
    failed[repomd_path])
Message: 'Download failed: %s (HTTP CODE %d)'
Arguments: ('https://cdn.redhat.com/content/dist/rhel/workstation/7/7Workstation/x86_64/optional/os/repodata/repomd.xml', None)

**Comment by ggainey** [comment]
Hey Eric - so with this change, if I start everything up, turn off webapp, and then run reposcan, when it tries to tell webapp to refresh it still throws a pretty nasty stacktrace:

```
vmaas-reposcan | 2018-04-19 13:37:52,716 __main__: [ERROR] Traceback (most recent call last):
vmaas-reposcan |   File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
vmaas-reposcan |     (self.host, self.port), self.timeout, **extra_kw)
vmaas-reposcan |   File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 60, in create_connection
vmaas-reposcan |     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
vmaas-reposcan |   File "/usr/lib64/python3.6/socket.py", line 745, in getaddrinfo
vmaas-reposcan |     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
vmaas-reposcan | socket.gaierror: [Errno -2] Name or service not known
vmaas-reposcan | During handling of the above exception, another exception occurred:
vmaas-reposcan | Traceback (most recent call last):
vmaas-reposcan |   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
vmaas-reposcan |     chunked=chunked)
vmaas-reposcan |   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 357, in _make_request
vmaas-reposcan |     conn.request(method, url, **httplib_request_kw)
vmaas-reposcan |   File "/usr/lib64/python3.6/http/client.py", line 1239, in request
vmaas-reposcan |     self._send_request(method, url, body, headers, encode_chunked)
vmaas-reposcan |   File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
vmaas-reposcan |     self.endheaders(body, encode_chunked=encode_chunked)
vmaas-reposcan |   File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
vmaas-reposcan |     self._send_output(message_body, encode_chunked=encode_chunked)
vmaas-reposcan |   File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
vmaas-reposcan |     self.send(msg)
vmaas-reposcan |   File "/usr/lib64/python3.6/http/client.py", line 964, in send
vmaas-reposcan |     self.connect()
vmaas-reposcan |   File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 166, in connect
vmaas-reposcan |     conn = self._new_conn()
vmaas-reposcan |   File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 150, in _new_conn
vmaas-reposcan |     self, "Failed to establish a new connection: %s" % e)
vmaas-reposcan | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f7b2c712eb8>: Failed to establish a new connection: [Errno -2] Name or service not known
vmaas-reposcan | During handling of the above exception, another exception occurred:
vmaas-reposcan | Traceback (most recent call last):
vmaas-reposcan |   File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
vmaas-reposcan |     timeout=timeout
vmaas-reposcan |   File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
vmaas-reposcan |     _stacktrace=sys.exc_info()[2])
vmaas-reposcan |   File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
vmaas-reposcan |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
vmaas-reposcan | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='webapp', port=8079): Max retries exceeded with url: /api/internal/refresh (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b2c712eb8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
vmaas-reposcan | During handling of the above exception, another exception occurred:
vmaas-reposcan | Traceback (most recent call last):
vmaas-reposcan |   File "/vmaas-reposcan/reposcan.py", line 186, in _notify_webapp
vmaas-reposcan |     response = requests.get(refresh_url)
vmaas-reposcan |   File "/usr/lib/python3.6/site-packages/requests/api.py", line 72, in get
vmaas-reposcan |     return request('get', url, params=params, **kwargs)
vmaas-reposcan |   File "/usr/lib/python3.6/site-packages/requests/api.py", line 58, in request
vmaas-reposcan |     return session.request(method=method, url=url, **kwargs)
vmaas-reposcan |   File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
vmaas-reposcan |     resp = self.send(prep, **send_kwargs)
vmaas-reposcan |   File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
vmaas-reposcan |     r = adapter.send(request, **kwargs)
vmaas-reposcan |   File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 508, in send
vmaas-reposcan |     raise ConnectionError(e, request=request)
vmaas-reposcan | requests.exceptions.ConnectionError: HTTPConnectionPool(host='webapp', port=8079): Max retries exceeded with url: /api/internal/refresh (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7b2c712eb8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
vmaas-reposcan | 2018-04-19 13:37:52,716 __main__: [ERROR] Unable to connect to http://webapp:8079/api/internal/refresh.
```

**Comment by eherget** [comment]
I'll work on a fix for this scenario and update the PR.

**Comment by eherget** [comment]
PR has been updated.  We were explicitly logging the traceback when failing to connect.  I changed it so it logs detailed info about the failure to connect, but not the full traceback.

One question... this is currently an Error level log message.  Since this webapp notify is only for dev support and not for the eventual GA way of running things, should this be a Warning, or even Info level message?
