### ISSUE TITLE
webapp gets into corrupted state

### ISSUE THREAD

**Issue by jdobes** [RedHatInsights/vmaas#263]
found in logs:

```ERROR:tornado.access:500 POST /api/v1/updates/ (10.130.10.1) 16181.89ms
ERROR:tornado.application:Uncaught exception POST /api/v1/updates/ (10.130.4.1)
HTTPServerRequest(protocol='http', host='webapp-vmaas-ci.1b13.insights.openshiftapps.com', method='POST', uri='/api/v1/updates/', version='HTTP/1.1', remote_ip='10.130.4.1', headers={'Content-Length': '45221', 'Forwarded': 'for=185.108.120.60;host=webapp-vmaas-ci.1b13.insights.openshiftapps.com;proto=http', 'X-Forwarded-Host': 'webapp-vmaas-ci.1b13.insights.openshiftapps.com', 'X-Forwarded-Port': '80', 'X-Forwarded-For': '185.108.120.60', 'User-Agent': 'tsung', 'Host': 'webapp-vmaas-ci.1b13.insights.openshiftapps.com', 'X-Forwarded-Proto': 'http', 'Content-Type': 'application/x-www-form-urlencoded'})
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/tornado/web.py", line 1368, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 313, in wrapped
    ret = fn(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/tornado/web.py", line 1580, in future_complete
    f.result()
  File "/usr/lib64/python2.7/site-packages/tornado/concurrent.py", line 214, in result
    raise_exc_info(self._exc_info)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 876, in run
    yielded = self.gen.throw(*exc_info)
  File "/app/app.py", line 234, in post
    res = yield self.background_process(endpoint='/updates', data=data)
  File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 870, in run
    value = future.result()
  File "/usr/lib/python2.7/site-packages/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/usr/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/app/app.py", line 55, in background_process
    db_instance = Database()
  File "/app/database.py", line 32, in __init__
    port=self.port)
  File "/usr/lib64/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
OperationalError: FATAL: remaining connection slots are reserved for non-replication superuser connections
```

currently, there seems to be new connection every request, opening this only for tracking, this issue will be resolved when webapp starts using cached data only

**Comment by grinrag** [comment]
We have
