### ISSUE TITLE
VERSION 0.5 api: errata: ISE during processing enhancement erratum

### ISSUE THREAD

**Issue by grinrag** [RedHatInsights/vmaas#341]
I've got ISE 500 with traceback for the erratum RHEA-2010:0932:
```python
ERROR:tornado.access:500 POST /api/v1/errata (10.130.10.1) 22.18ms
ERROR:tornado.application:Uncaught exception GET /api/v1/errata/RHEA-2010:0932 (10.130.10.1)
HTTPServerRequest(protocol='http', host='webapp-vmaas-stage.1b13.insights.openshiftapps.com', method='GET', uri='/api/v1/errata/RHEA-2010:0932', version='HTTP/1.1', remote_ip='10.130.10.1')
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/tornado/web.py", line 1543, in _execute
    result = yield result
  File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 1099, in run
    value = future.result()
  File "/usr/lib64/python3.6/site-packages/tornado/gen.py", line 315, in wrapper
    yielded = next(result)
  File "/app/app.py", line 440, in get
    res = self.errata_api.process_list({'errata_list': [erratum]})
  File "/app/errata.py", line 84, in process_list
    "package_list": self.pkgidlist2packages(errata_detail[ERRATA_PKGIDS]),
  File "/app/errata.py", line 30, in pkgidlist2packages
    name = cch.id2packagename[cch.package_details[pkg_id][0]]
KeyError: 65693
```

**Comment by grinrag** [comment]
Looks like it fixed in the master. Just gonna rebase 0.5 on the master.
