### ISSUE TITLE
BATCH_SIZE=100 runs reposcan out of space 

### ISSUE THREAD

**Issue by ggainey** [RedHatInsights/vmaas#428]
When sync'ing enough 'real' repositories, along with cve and cvemap at 'the same time', it's entirely possible to run reposcan out of the 14G default disk in an openshift img when trying to handle 100 repositories per-batch. We should reduce to 50 - better to run at half-speed, reliably, than full-speed till crash

Failure mode is the following error-logs inm quick succession:

```
__main__: [ERROR] Internal server error <-9223363269965417020>'Traceback (most recent call last):\n  File "/vmaas-reposcan/reposcan.py", line 684, in run_task\n    controller.store()\n  File "/vmaas-reposcan/nistcve/cve_controller.py", line 111, in store\n    failed = self._download_meta()\n  File "/vmaas-reposcan/nistcve/cve_controller.py", line 38, in _download_meta\n    repo.tmp_directory = tempfile.mkdtemp(prefix="cverepo-")\n  File "/usr/lib64/python3.6/tempfile.py", line 370, in mkdtemp\n    _os.mkdir(file, 0o700)\nOSError: [Errno 28] No space left on device: \'/tmp/cverepo-s3qdfkab\''|

__main__: [ERROR] Internal server error <-9223363269965417020>'Traceback (most recent call last):\n  File "/vmaas-reposcan/reposcan.py", line 728, in run_task\n    controller = CvemapController()\n  File "/vmaas-reposcan/redhatcve/cvemap_controller.py", line 29, in __init__\n    self.tmp_directory = tempfile.mkdtemp(prefix="cvemap-")\n  File "/usr/lib64/python3.6/tempfile.py", line 370, in mkdtemp\n    _os.mkdir(file, 0o700)\nOSError: [Errno 28] No space left on device: \'/tmp/cvemap-_g2x7b8g\''

__main__: [ERROR] Internal server error <-9223363270013434092>'Traceback (most recent call last):\n  File "/vmaas-reposcan/reposcan.py", line 638, in run_task\n    repository_controller.store()\n  File "/vmaas-reposcan/repodata/repository_controller.py", line 222, in store\n    self._write_certificate_cache()\n  File "/vmaas-reposcan/repodata/repository_controller.py", line 182, in _write_certificate_cache\n    self.certs_tmp_directory = tempfile.mkdtemp(prefix="certs-")\n  File "/usr/lib64/python3.6/tempfile.py", line 370, in mkdtemp\n    _os.mkdir(file, 0o700)\nOSError: [Errno 28] No space left on device: \'/tmp/certs-0ftg49q8\''
```

**Comment by ggainey** [comment]
After cleaning out /tmp and asking reposcan to resync, I was completely unable to reproduce. I think what happened, is a sequence something like "large repos had a lot of changes, unpacking them ran /tmp out of space and reposcan threw an ISE, reposcan failed to clean up the repos it was working on, everything after that fails until someone logs in and manually cleans things up." In addition to lowering BATCH_SIZE, we should prob scrutinize reposcan's failure-path and make sure it cleans up after itself even if/when it has problems.
