### ISSUE TITLE
Internal server error when modules_list is invalid

### ISSUE THREAD

**Issue by psegedy** [RedHatInsights/vmaas#465]
For example `curl -d@updates_modules.json -k http://localhost:8080/api/v1/updates`
```
(.venv) ➜  iqe-vulnerability-plugin git:(modularity_tests) ✗ cat updates_modules.json 
{
  "package_list": ["postgresql-10.5-1.el8+1546+27ad5f8e.x86_64"],
  "modules_list":[{"a": "b"}]
}%  
```
Throws KeyError: 'module_name'
```
vmaas-webapp       | e6ebccaee2af 2019-03-12 17:36:33,334 __main__: [ERROR] Internal server error <-9223363303110034475>: please include this error id in bug report.'Traceback (most recent call last):
  File "/webapp/app.py", line 105, in handle_post
    res = api_endpoint.process_list(api_version, data)
  File "/webapp/updates.py", line 381, in process_list
    module_info = [(x['module_name'], x['module_stream']) for x in modules_list]
  File "/webapp/updates.py", line 381, in <listcomp>
    module_info = [(x['module_name'], x['module_stream']) for x in modules_list]
KeyError: 'module_name''|
vmaas-webapp       | e6ebccaee2af 2019-03-12 17:36:33,335 __main__: [INFO] Input data for <-9223363303110034475>: {'package_list': ['postgresql-10.5-1.el8+1546+27ad5f8e.x86_64'], 'modules_list': [{'a': 'b'}]}
vmaas-webapp       | e6ebccaee2af 2019-03-12 17:36:33,336 tornado.access: [ERROR] 500 POST /api/v1/updates (172.18.0.1) 3.89ms
```

**Comment by blayson** [comment]
Currently, it logs this
`vmaas-webapp       | 88298d716b0d 2019-07-01 14:10:49,568 __main__: [ERROR] ValidationError: 0 : 'module_name' is a required property `

**Comment by jdobes** [comment]
Based on previous comment, closing this issue as already fixed. Please re-open if not.
