### ISSUE TITLE
Reposync IntegrityError: duplicate key value

### ISSUE THREAD

**Issue by psegedy** [RedHatInsights/vmaas#469]
With following repolist:
```yaml
[{
  "products": {
    "VMaaS testing - modularity": {
      "content_sets": {
        "vmaas-test-rhel8-module": {
          "name": "VMaaS testing RHEL8 modularity repo",
          "baseurl": "http://<ping me for url>/repodata-for-vmaas/module_repo/",
          "basearch": ["x86_64"],
          "releasever": ["8"]
        }
      }
    },
    "Red Hat Enterprise Linux Server": {
      "content_sets": {
        "rhel-7-server-rpms": {
          "name": "Red Hat Enterprise Linux 7 Server (RPMs)",
          "baseurl": "http://<ping me for url>/repodata-for-vmaas/rhel/server/7/$releasever/$basearch/os/",
          "basearch": ["x86_64"],
          "releasever": ["7Server"]
        }
      }
    }
  }
}]

```
```python
__main__: [ERROR] Internal server error <-9223363244935041908>'Traceback (most recent call last):
  File "/reposcan/repodata/repository_controller.py", line 257, in store
    self.repo_store.store(repository)
  File "/reposcan/database/repository_store.py", line 171, in store
    self.package_store.store(repo_id, repository.list_packages())
  File "/reposcan/database/package_store.py", line 202, in store
    package_ids = self._populate_packages(packages)
  File "/reposcan/database/package_store.py", line 141, in _populate_packages
    self._populate_dependent_tables(packages)
  File "/reposcan/database/package_store.py", line 138, in _populate_dependent_tables
    self._populate_package_names(unique_names)
  File "/reposcan/database/package_store.py", line 117, in _populate_package_names
    to_import, page_size=len(to_import))
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/site-packages/psycopg2/extras.py", line 1278, in execute_values
    cur.execute(b''.join(parts))
psycopg2.IntegrityError: duplicate key value violates unique constraint "package_name_name_key"
DETAIL:  Key (name)=(mariadb-server) already exists.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/reposcan/reposcan.py", line 642, in run_task
    repository_controller.store()
  File "/reposcan/repodata/repository_controller.py", line 262, in store
    self.repo_store.cleanup_unused_data()
  File "/reposcan/database/repository_store.py", line 86, in cleanup_unused_data
    """)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block
```

NOTE: It is not always reproducible. Happened to me in 60% of syncs.

**Comment by jdobes** [comment]
according to @psegedy this has already been fixed
